name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '📜 Documentation'
    labels:
      - 'docs'
  - title: '🏗️ Build'
    labels:
      - 'build'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feat'
      - 'fix'
  patch:
    labels:
      - 'docs'
      - 'chore'
      - 'refactor'
  default: patch
template: |
  ## Changes

  $CHANGES