name: Fetch Release Notes

on:
  release:
    types: [published]

jobs:
  fetch-and-push-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Clone Central Repository
        run: git clone https://github.com/Tengizo/release-central.git release-central

      - name: Fetch Release Notes
        run: |
          REPO_NAME="${REPO_NAME##*/}"
          mkdir -p $REPO_NAME
          MD_FILE=$REPO_NAME/${{ github.event.release.tag_name }}.md
          gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --json body -q .body > $MD_FILE
          sed -E 's|@([a-zA-Z0-9_-]+)|[@\1](https://github.com/\1)|g; s|#([0-9]+)|[#\1](https://github.com/${{ github.repository }}/pull/\1)|g' $MD_FILE > release-central/$MD_FILE
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "TARGET_DIR=${REPO_NAME}" >> $GITHUB_ENV
          echo "SOURCE_DIR=release-central/${REPO_NAME}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: "${{ github.repository }}"
      - name: Log
        run: |
          echo "Source directory ${{ env.SOURCE_DIR }}"
          echo "Target directory ${{ env.TARGET_DIR }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: "${{ github.repository }}"
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: ${{ env.SOURCE_DIR }}
          destination-github-username: 'Tengizo'
          destination-repository-name: 'release-central'
          target-directory: ${{ env.TARGET_DIR }}
          user-email: chtengo@gmail.com
          target-branch: master
          commit-message:  Add release notes ${{ github.event.release.tag_name }} for ${{ github.repository }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#      - name: Create and Push Release Notes
#        run: |
#          cd release-central
#          REPO_NAME="${REPO_NAME##*/}"
#          mkdir -p $REPO_NAME
#          RELEASE_NOTES=$(<../release-notes.txt)
#          echo "${RELEASE_NOTES}" > $REPO_NAME/${{ github.event.release.tag_name }}
#          git add .
#          git commit -m "Add release notes for $REPO_NAME@${{ github.event.release.tag_name }}"
#          git push
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          REPO_NAME: "${{ github.repository }}"

